const BASE_DIR_IMAGE = 'https://github.com/asrofilfachrulr/keranjang-belanja-vue/raw/main/public/images/'

export const list = [
    {
        name: "Indomie Goreng Rendang",
        desc: "Masakan Instan Terenak di Dunia",
        longDesc: "Indomie Goreng rasa Rendang 3000.an dengan berbagai topping:<br>- potongan daging Wagyu A6 A6 joz<br>- tamago (telur, --jepang)<br>- Cabbage (kubis, --jaksel)<br>- chili slices (artiin sendiri)",
        stock: 1500,
        price: 3999,
        src: BASE_DIR_IMAGE + "indomie-rendang.jpg",
    },
    {
        name: "Mie Gelas Rendang",
        desc: "Masakan Instan Khusus Anak Kostan",
        longDesc: "Mie homemade icik iwir disajikan dalam gelas (cup) rasa bumbu rendang asli, pedas dengan topping:<br>-ayam suwir<br>- saus padang<br>- potongan cabe<br>- bawang goreng",
        stock: 10000,
        price: 899,
        src: BASE_DIR_IMAGE + "mie-gelas.jpg",
    },
    {
        name: "Bakmi Mewah",
        desc: "Stop Makan Ini Ya..",
        longDesc: "Bakmi mewah dua bungkus dicampur dengan bumbu rahasia (gimmick) beserta topping<br>- dried meatball<br>- nori",
        stock: 100,
        price: 19999,
        src: BASE_DIR_IMAGE + "bakmi-mewah.jpg",
    },
    {
        name: "Sarden Joss",
        desc: "Jangan Makan Kalo Belum Joss",
        longDesc: "Sarden kaleng(an) disajikan (di piring, dimana lagi? kamu nanyea?) dengan tumis lobak dan ekstra saus tomat rahasia (gimmick juga)",
        stock: 150,
        price: 7999,
        src: BASE_DIR_IMAGE + "sarden-bca.jpg",
    },
    {
        name: "Mix-sulek",
        desc: "Ice Cream Republik Rakyat Konoha",
        longDesc: "Vanilla sundae dengan cream toping boba, choco chips dan strawberry paste",
        stock: 100,
        price: 5999,
        src: BASE_DIR_IMAGE + "mixsuek.jpg",
    },
    {
        name: "Smashed Chicken",
        desc: "Makanan Tendangan Ayam",
        longDesc: "Ayam geprek hot uhuy sambal bawang dengan timun dan tomat, level pedas request langsung ke kasir",
        stock: 120,
        price: 15999,
        src: BASE_DIR_IMAGE + "smashed-chicken.png",
    },
    {
        name: "Hot Americano Gula Aren",
        desc: "Kopi Ala ala Orang Kaya",
        longDesc: "Americano gula aren, diaduk clockwise 3 kali khusus kaum elit, ekspatriat, influencer, dan punya KTP jaksel. Kaum checkout nunggu diskon minggir dulu",
        stock: 200,
        price: 29999,
        src: BASE_DIR_IMAGE + "setarbak.jpg",
    },
]